baseURL: "https://tech.tf1.fr/"
languageCode: "fr-FR"
title: "Blog technique e-TF1"
theme: "hugo-theme-novela-tf1plus"
pygmentsstyle: "monokai"
paginate: 6
social:
  2_linkedin: "https://www.linkedin.com/company/e-tf1/"
  3_github: "https://github.com/etf1"
  4_rss: "https://tech.tf1.fr/index.xml"
  1_welcome_to_the_jungle: "https://www.welcometothejungle.com/fr/companies/groupe-tf1"
markup:
   defaultMarkdownHandler: goldmark
   goldmark:
     hrefTargetBlank: 1
enableRobotsTXT: true
params:
  description: "Découvrez les coulisses de TF1+, la plateforme de streaming vidéo de TF1"
  seo:
    default_image: "/images/tf1plus.png"
    locale: "fr_FR"
    keywords: "mytf1, tf1, tf1+, streaming, player, video, go, golang, react, js, javascript, css, android, ios, kotlin, swift, nginx, drm, widevine, elemental, aws, mongodb, kafka"